"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var main_1 = require("./main");
var cellTimetable_1 = require("./cellTimetable");
var timetable_1 = require("./timetable");
var teacher_1 = require("./teacher");
var subject_1 = require("./subject");
var office_1 = require("./office");
var group_1 = require("./group");
var restApi = express_1.Router();
exports.restApi = restApi;
restApi.use('/main', main_1.adminApi);
restApi.use('/main/timetable', timetable_1.timetableApi);
restApi.use('/main/cellTimetable', cellTimetable_1.cellTimetableApi);
restApi.use('/main/teacher', teacher_1.teacher);
restApi.use('/main/subject', subject_1.subject);
restApi.use('/main/office', office_1.office);
restApi.use('/main/group', group_1.group);
//# sourceMappingURL=index.js.map